services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  nodered:
    image: nodered/node-red:latest
    user: "1000:1000"
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
      - ./signatures:/signatures
    depends_on:
      - mosquitto

volumes:
  mosquitto_data:
  mosquitto_log:
  nodered_data:
